# Main site configuration
[build]
  base = "main-site" # The directory containing your main site project
  publish = "main-site/dist" # Adjust "dist" to your build output folder
  command = "npm run build" # Build command for the main site

# Subdomain configuration
[[context.deploy-preview]]
  publish = "subdomain-site/dist" # Adjust "dist" for the subdomain build output folder
  command = "npm run build" # Build command for the subdomain site

[[redirects]]
  from = "/links/*"
  to = "https://links.dylangl.netlify.app/:splat"
  status = 301
